In [9]:
import numpy as np

# Define matrices A and B
A = np.array([[-1, 2], [4, -1]])
B = np.array([[2, -3], [-4, 1]])

# Calculate the products AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

# Find C = AB - BA
C = AB - BA

print("Matrix C = AB - BA:")
print(C)


Matrix C = AB - BA:
[[ 4 -2]
 [ 4 -4]]


In [12]:
import numpy as np

# Define the matrix A
A = np.array([[-1, -2], [0, 1]])

# Exponentiate matrix A (for example, let's calculate A^2)
n = 2
result = np.linalg.matrix_power(A, n)

print(f"Matrix A^2:")
print(result)


Matrix A^2:
[[1 0]
 [0 1]]


In [1]:
import numpy as np

# Define matrices A and B
A = np.array([[3, 5], [6, -1]])
B = np.array([[2, 1], [-3, 2]])

# Calculate the product of A and B
product = np.dot(A, B)

print("Matrix A:")
print(A)

print("Matrix B:")
print(B)

print("Product of matrices A and B:")
print(product)


Matrix A:
[[ 3  5]
 [ 6 -1]]
Matrix B:
[[ 2  1]
 [-3  2]]
Product of matrices A and B:
[[-9 13]
 [15  4]]


In [2]:
import numpy as np

# Define the matrix
matrix = np.array([[2, 3, 4], [1, 0, 6], [7, 8, 9]])

# Calculate the determinant
determinant = np.linalg.det(matrix)

print("Matrix:")
print(matrix)

print("Determinant:")
print(determinant)


Matrix:
[[2 3 4]
 [1 0 6]
 [7 8 9]]
Determinant:
35.00000000000001


In [4]:
import numpy as np

# Define the 4x4 matrix
matrix = np.array([[2, 3, 4, 1], [1, 2, 3, 4], [3, 4, 1, 2], [4, 1, 2, 3]])

# Calculate the determinant
determinant = np.linalg.det(matrix)

print("Matrix:")
print(matrix)

print("Determinant:")
print(determinant)


Matrix:
[[2 3 4 1]
 [1 2 3 4]
 [3 4 1 2]
 [4 1 2 3]]
Determinant:
-160.00000000000009


In [5]:
import numpy as np

# Define the matrix
matrix = np.array([[1, 2, -3], [0, 1, 2], [0, 0, 1]])

# Calculate the inverse matrix
inverse_matrix = np.linalg.inv(matrix)

print("Matrix:")
print(matrix)

print("Inverse Matrix:")
print(inverse_matrix)


Matrix:
[[ 1  2 -3]
 [ 0  1  2]
 [ 0  0  1]]
Inverse Matrix:
[[ 1. -2.  7.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]]


In [6]:
import numpy as np

# Define the matrix
matrix = np.array([[1, 2, 3, 4], [3, -1, 2, 5], [1, 2, 3, 4], [1, 3, 4, 5]])

# Calculate the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

print("Matrix:")
print(matrix)

print("Rank of the matrix:", rank)


Matrix:
[[ 1  2  3  4]
 [ 3 -1  2  5]
 [ 1  2  3  4]
 [ 1  3  4  5]]
Rank of the matrix: 2


In [7]:
import numpy as np

# Define the coefficient matrix A and the constant vector B
A = np.array([[2, -1, 1],
              [3, 4, -2],
              [1, -3, 1]])

B = np.array([5, -3, 4])

# Calculate the determinant of A
det_A = np.linalg.det(A)

# Check if the determinant is close to zero (singular matrix)
if abs(det_A) < 1e-10:
    print("The matrix A is singular. The system may have no solution or infinitely many solutions.")
else:
    # Create a copy of A and replace columns with B
    A1 = A.copy()
    A1[:, 0] = B

    A2 = A.copy()
    A2[:, 1] = B

    A3 = A.copy()
    A3[:, 2] = B

    # Calculate the solutions using the Kramer method
    x = np.linalg.det(A1) / det_A
    y = np.linalg.det(A2) / det_A
    z = np.linalg.det(A3) / det_A

    print("Using Kramer's method:")
    print(f"x = {x}, y = {y}, z = {z}")

    # Verify the solution using the solve() function
    solution = np.linalg.solve(A, B)
    print("Using numpy.linalg.solve():")
    print("x =", solution[0])
    print("y =", solution[1])
    print("z =", solution[2])


Using Kramer's method:
x = 1.0, y = 7.771561172376072e-16, z = 3.0
Using numpy.linalg.solve():
x = 1.0
y = -2.7328566760003855e-16
z = 2.9999999999999996


In [8]:
import numpy as np

# Define the dimensions of the matrix
N = 5  # Number of rows
M = 4  # Number of columns

# Create a random matrix A with N rows and M columns
A = np.random.rand(N, M)

# Calculate the sum of absolute values for each column
column_sums = np.sum(np.abs(A), axis=0)

# Find the column with the smallest minimum absolute element
min_abs_elements = np.min(np.abs(A), axis=0)
max_sum_column = np.argmax(column_sums)

print("Matrix A:")
print(A)

print("Sum of absolute values for each column:")
print(column_sums)

print(f"Column with the smallest minimum absolute element and the largest sum: Column {max_sum_column + 1}")
print(f"Minimum absolute element in this column: {min_abs_elements[max_sum_column]}")


Matrix A:
[[0.35398664 0.11996353 0.26167388 0.27178285]
 [0.78585243 0.20146362 0.82451034 0.60490936]
 [0.54024286 0.87108684 0.67014242 0.16873901]
 [0.67372055 0.80234251 0.71349221 0.37034445]
 [0.61451867 0.35970825 0.94217003 0.82538429]]
Sum of absolute values for each column:
[2.96832115 2.35456475 3.41198888 2.24115995]
Column with the smallest minimum absolute element and the largest sum: Column 3
Minimum absolute element in this column: 0.2616738813691668
